image:
  file: .gitpod.Dockerfile
tasks:
  - init: abtnode init -f --no-https
    command: abtnode start && node echo-endpoint.js
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 8088
    onOpen: ignore
  - port: 8089
    onOpen: ignore
  - port: 40404
    onOpen: ignore
  - port: 40405
    onOpen: ignore
  - port: 40406
    onOpen: ignore
  - port: 40407
    onOpen: ignore
